# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: /
title: Header Consultoria
# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #



# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #


contacttitle: Agende uma reunião
contacturl: https://calendly.com/headerconsultoria
